# Generated by Django 5.2.4 on 2025-07-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=100, verbose_name="ファイル名"),
                ),
            ],
            options={
                "verbose_name": "画像ファイル",
                "db_table": "image_file",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="店舗名")),
                ("value", models.IntegerField(verbose_name="店舗評価")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="店舗説明"),
                ),
                (
                    "shop_cite",
                    models.TextField(blank=True, null=True, verbose_name="店舗サイト"),
                ),
                (
                    "import_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.imagefile",
                        verbose_name="写真ファイルID",
                    ),
                ),
            ],
            options={
                "verbose_name": "店舗",
                "db_table": "shop",
            },
        ),
    ]
