# Generated by Django 5.2.4 on 2025-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="import_file",
            new_name="image_file",
        ),
        migrations.RemoveField(
            model_name="imagefile",
            name="file_name",
        ),
        migrations.AddField(
            model_name="imagefile",
            name="image",
            field=models.ImageField(
                default="shop_images/default.jpg",
                upload_to="images/",
                verbose_name="画像ファイル",
            ),
        ),
    ]
