# Generated by Django 5.2.4 on 2025-07-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_rename_import_file_shop_image_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="value",
            field=models.FloatField(verbose_name="店舗評価"),
        ),
    ]
