# Generated by Django 5.2.4 on 2025-07-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_shop_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="shop_cite",
            new_name="cite",
        ),
    ]
