# Generated by Django 5.2.4 on 2025-07-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_rename_shop_cite_shop_cite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="image_file",
            new_name="image",
        ),
    ]
