# Generated by Django 5.2.4 on 2025-07-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_rename_image_file_shop_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="image",
            new_name="image_file",
        ),
    ]
