# Generated by Django 5.2.4 on 2025-07-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_rename_image_shop_image_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagefile",
            old_name="image",
            new_name="url",
        ),
    ]
